target 'DolphiniOS' do
    platform :ios, '12.0'
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
    pod 'UICollectionViewLeftAlignedLayout'
end

target 'DolphinATV' do
    platform :tvos, '14.0'
end
