def common_pods
    pod 'UICollectionViewLeftAlignedLayout', :git => 'https://github.com/OatmealDome/UICollectionViewLeftAlignedLayout/'end

target 'DolphiniOS' do
    platform :ios, '12.0'
    common_pods
    pod 'Firebase/Analytics'
    pod 'Firebase/Crashlytics'
end

target 'DolphinATV' do
    platform :tvos, '14.0'
    common_pods
end
